apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: immortalcontainers.immortalcontainers.flugel.it
spec:
  group: immortalcontainers.flugel.it
  names:
    kind: ImmortalContainer
    listKind: ImmortalContainerList
    plural: immortalcontainers
    singular: immortalcontainer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              minLength: 1
              type: string
          required:
          - image
          type: object
        status:
          properties:
            currentPod:
              type: string
          type: object
  version: v1alpha1
